version: "1.0"
stages:
  - "clone"
  - "build"
  - versioning
  - "push"
steps:
  clone_init:
    title: Init Clone
    stage: clone
    image: codefresh/cli
    shell: bash
    commands:
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
      - cf_export CICD_INFO_PATH="/codefresh/volume/cicd.git/${{CF_REPO_NAME}}"
  main_clone:
    type: "git-clone"
    title: Clone Main Repo
    description: "Cloning main repository..."
    repo: "kubevious/kubevious"
    revision: "${{CF_BRANCH}}"
    stage: clone
  cicd_clone:
    title: Clone CI/CD Repo
    stage: clone
    image: 'alpine/git:latest'
    working_directory: "${{main_clone}}/.."
    commands:
      - pwd
      - ls -la
      - rm -rf cicd.git
      - 'git clone https://${{CF_REPO_OWNER}}:$GITHUB_TOKEN@github.com/${{CF_REPO_OWNER}}/cicd.git cicd.git'
      - ls -la
      - ls -la cicd.git/
  debug_output:
    title: Debug Output
    stage: build
    image: codefresh/cli
    shell: bash
    commands:
      - env
      - echo "$CF_BRANCH_TAG_NORMALIZED"
  build:
    title: "Building Docker Image"
    type: build
    image_name: "kubevious/kubevious"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    stage: build
  process_versioning:
    title: Process Versioning
    stage: build
    image: codefresh/cli
    shell: bash
    working_directory: "${{CICD_INFO_PATH}}"
    commands:
      - pwd
      - ls -la
      - ../process-version-bump.sh
      - echo "PRODUCT_VERSION=${PRODUCT_VERSION}"
  push:
    title: "Pushing image to DockerHub"
    type: "push"
    stage: "push"
    image_name: "kubevious/kubevious"
    registry: "dockerhub"
    candidate: "${{build}}"
    tags:
      - latest
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
