kubevious:
  image:
    repository: kubevious/kubevious
    tag: latest
    pullPolicy: Always
  name: kubevious
  svcName: kubevious-svc
  port: 4000

ui:
  image:
    repository: kubevious/ui
    tag: latest
    pullPolicy: Always
  name: kubevious-ui
  svcName: kubevious-ui-svc
  port: 3000
